mymodule.settings:
  type: config_object
  label: 'Mymodule settings'
  mapping:
    country:
      type: string
      label: "Country"
    city:
      type: string
      label: "Weather of the city"
    apikey:
      type: string
      label: "Apikey of the weather api"
    apiendpoint:
      type: string
      label: "Api endpoint of weather api"
action.configuration.mymodule:
  type: featured_node_action
  label: 'Featured Node'
realname.settings:
  type: config_object
  label: 'Realname settings'
  mapping:
    first_name:
      type: char
      label: "Firstname"
      length: 255
    last_name:
      type: char
      label: "Lastname"
      length: 255
